# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170919_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.TextField()),
                ('env', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('debug', models.TextField()),
            ],
        ),
    ]
