# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ideal_reality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Python',
            new_name='Py',
        ),
    ]
