# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_essay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideal_reality',
            name='reality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ideal_reality',
            name='reality_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
