# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171009_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debug',
            name='bug',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='debug',
            name='debug',
            field=models.TextField(blank=True),
        ),
    ]
