# Generated by Django 2.0.1 on 2018-01-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='Py',
        ),
    ]
