# Generated by Django 2.0.1 on 2018-01-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180129_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideal_reality',
            old_name='ideal_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='debug',
            name='env',
        ),
        migrations.RemoveField(
            model_name='ideal_reality',
            name='reality_timestamp',
        ),
    ]
