# Generated by Django 2.0.1 on 2018-01-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180129_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debug',
            old_name='bug',
            new_name='que',
        ),
        migrations.RenameField(
            model_name='debug',
            old_name='debug',
            new_name='sol',
        ),
    ]
