# Generated by Django 2.0.7 on 2018-08-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgurl',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='siteurl',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(editable=False),
        ),
    ]
