# Generated by Django 2.0.7 on 2018-08-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180802_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imgurl',
            field=models.CharField(max_length=150),
        ),
    ]
